
package supersquare;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SuperSquareService", targetNamespace = "http://supersquare/", wsdlLocation = "http://localhost:8888/supersquare?WSDL")
public class SuperSquareService
    extends Service
{

    private final static URL SUPERSQUARESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(supersquare.SuperSquareService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = supersquare.SuperSquareService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/supersquare?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/supersquare?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SUPERSQUARESERVICE_WSDL_LOCATION = url;
    }

    public SuperSquareService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SuperSquareService() {
        super(SUPERSQUARESERVICE_WSDL_LOCATION, new QName("http://supersquare/", "SuperSquareService"));
    }

    /**
     * 
     * @return
     *     returns SuperSquare
     */
    @WebEndpoint(name = "SuperSquarePort")
    public SuperSquare getSuperSquarePort() {
        return super.getPort(new QName("http://supersquare/", "SuperSquarePort"), SuperSquare.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SuperSquare
     */
    @WebEndpoint(name = "SuperSquarePort")
    public SuperSquare getSuperSquarePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://supersquare/", "SuperSquarePort"), SuperSquare.class, features);
    }

}
